# Generated by Django 4.2.3 on 2023-07-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='passkey',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
